### ISSUE TITLE
Using data that is not entirely sequential

### ISSUE THREAD

**Issue by UltraSpecialException** [bryanlimy/tf2-transformer-chatbot#2]
Hi. First of all, thank you so much for writing this project and the article on medium explaining the code.

As I've read the code, I see that for your data, you build 2 arrays: `questions` and `answers` where `answers[i]` is the response to `questions[i]`. I looked through data files, and although the conversations are broken up to individual lines, the entire movie seems to have a sequential nature to it. What I mean is that, for example, the first 2 lines of the `movie_conversations.txt` have:
u0 +++$+++ u2 +++$+++ m0 +++$+++ ['L194', 'L195', 'L196', 'L197']
u0 +++$+++ u2 +++$+++ m0 +++$+++ ['L198', 'L199']

Although the lines ['L194', 'L195', 'L196', 'L197'] and ['L198', 'L199'] are separated into 2 conversations, the movie script still has that natural sequence where L197 and L198 still follow one another correspondingly. I suppose the data doesn't specify L198 to be a response to L197 though.

My main question is that: I'm using a collection of reddit comments threads, where I have access to trees of comments. So I will have separate conversations where the lines fit with one another, but there won't be any continuation after a comment tree ends like in the movie script. Would this affect the quality of the chat bot? If so, what would the difference be?

Thanks

**Comment by bryanlimy** [comment]
Hi, thanks for reaching out!
So I am not sure how the Cornell Movie Corpus split the conversation sequence, but it shouldn't matter to our model since only process a single conversation pair at a time, given the first `L194`, we predict `L195`. One major limitation with this current chatbot is that the model won't be coherent throughout a conversation, it doesn't remember what it heard and said in the past. 

So I think with the reddit dataset you have, it is going to behave similarly to the model trained on the movie corpus (except a lot more swear words and random memes), in the sense that it won't be able to remember what it has said in the past, it only focus on the given input and provide an output.

I hope this helps.

**Comment by UltraSpecialException** [comment]
I see. Thank you! 

Regarding the inability of the chatbot to retain previous information -- do you have any pointers to articles/tutorials that provide guidance on how to take this into account.

**Comment by bryanlimy** [comment]
Unfortunately, I haven't seen any end-to-end neural network chatbot that is able to maintain a coherent conversation. https://chatbotslife.com/how-to-build-a-conversational-chatbot-and-avoid-if-else-statements-37b48ad11eae, usually they require some sort of mechanism to store conversation information so that it can recall to information.

**Comment by UltraSpecialException** [comment]
Thanks, I'll definitely read it! :)
